### ISSUE TITLE
my Attiny13A require SCK pin (PB2) to pull to LOW to work properly.... I don't know what is going on...

### ISSUE THREAD

**Issue by GluTbl** [MCUdude/MicroCore#103]
I program a simple blink sketch to blink... the sketch dont work... but work when i connect the SCK (PB2) to ground..... why i require this????.....

**Comment by nerdralph** [comment]
My guess would be a bad ground connection.  Grounding PB2 would give a MCU ground of about 0.6V from the Vf of the input clamping diodes.
http://nerdralph.blogspot.com/2015/09/diodes-diodes-everywhere.html
http://3.bp.blogspot.com/-xE_Dcd_cTNU/VfSbb0PP-fI/AAAAAAAAinI/ks0swq_Uyas/s1600/ClampingDiodes.png

**Comment by GluTbl** [comment]
I don't know but some attiny13a work without putting the SCK to low... i think that one is faulty one.....

**Comment by MCUdude** [comment]
I recently tried to use an ATtiny13 that turned out to be faulty. On my chip. PB2 stayed low no matter what I did. I was trying to use it as a digital input. Swapping the chip for a different one solved the issue for me.

The application was a simple 230V switch with zero cross detection.
