### ISSUE TITLE
is tools.avrdude.program used?

### ISSUE THREAD

**Issue by nerdralph** [MCUdude/MicroCore#108]
https://github.com/MCUdude/MicroCore/blob/master/avr/platform.txt#L129

I've been experimenting with the boards.txt and platform.txt files, and can't figure out how avrdude.program is used.
avrdude.upload is used for upload and for the "Upload Using Programmer" menu.
avrdude.erase and avrdude.bootloader seem to be used by the "Burn Bootloader" menu.

Can it be removed, or is it actually used somehow?

**Comment by MCUdude** [comment]
Sorry, I'm currently on vacation. I see SpenceKonde did answer you, so I'll close this for now.
