### ISSUE TITLE
Wiring issue in "MicroCore ATtiny13 minimal setup"?

### ISSUE THREAD

**Issue by wmzart** [MCUdude/MicroCore#111]
In the MicroCore ATtiny13 minimal setup, shown here:

  https://github.com/MCUdude/MicroCore#minimal-setup

the ISP PROGRAMMING HEADER section shows at J1, pin 3: MOSI and at pin 4: SCK.

On my programmer however, Avr Dragon, pin 3 is SCK and pin 4 is MOSI, shown in section "3.3.1.1. SPI (ISP) Header (mounted)":

![Screenshot from 2020-08-02 11-34-20](https://user-images.githubusercontent.com/11244469/89120157-4977a100-d4b4-11ea-99fb-68e0858ccd3a.png)

(Source: http://ww1.microchip.com/downloads/en/devicedoc/atmel-42723-avr-dragon_userguide.pdf )

Are pins 3 and 4 wrongly swapped on the schematic drawing?

**Comment by MCUdude** [comment]
Thanks for reporting, you're absolutely right. Luckily, the ATtiny development board I sell does have the ISP wiring correct 🙂.
I'll fix it right away!

**Comment by wmzart** [comment]
I am glad the development board is correct. Strange though that no one noticed this before.

Please close this when fixed.
