### ISSUE TITLE
BOD low voltage lever around 3.3v disable attiny 

### ISSUE THREAD

**Issue by E3K4** [MCUdude/MicroCore#113]
When i change voltage to 3.3V  and BOD set to 2.7V on attiny13 just stop working while if bod is even set to 2.7V and Voltage given to vcc is 5V it all work fine oscilator is set to 4.8hz

**Comment by nerdralph** [comment]
I've never many good reasons for using anything other than 1.8V BOD.  The t13 (and most other AVRs) work fine at that voltage, including flash and eeprom writes.

**Comment by MCUdude** [comment]
If this should turn out to be an actual issue, It's not related to MicroCore at all.
