### ISSUE TITLE
MIDI 31250 Baud Rate

### ISSUE THREAD

**Issue by sharpie7** [MCUdude/MicroCore#126]
Thanks for creating this package. It really helped me out on a project this weekend.

Quick question/issue: MIDI uses a fixed Baud rate of 31250 (specified in the standard). Is support for this rate possible using the serial features of this library? If so, could the compatibility with the different CPU clocks be added to the table in core_settings.h ?

**Comment by MCUdude** [comment]
Hi! Great to hear you find MicroCore useful!

A baud rate of 31250 should absolutely work, even though I haven't tried it. If you run the ATtiny13 at 9.6 MHz you should be good. All you need to do is to change the baud rate number in core_settings.h. I'll see if I can test it myself and figure out which clock speeds support 31250 baud.

**Comment by sharpie7** [comment]
Many thanks.

**Comment by MCUdude** [comment]
31250 baud will work on all clock frequencies except for 600kHz and 128kHz.
