### ISSUE TITLE
Interrupts not enabled by default?

### ISSUE THREAD

**Issue by cbpdk** [MCUdude/MicroCore#127]
Just want to know if it is on purpose interrupts are not enabled by default?

Testing the PinChangeInterrupt library using no timers or other interrupts, at first nothing happened.
Only after adding a sei();/interrupts(); after attachPCINT did it work.

Because the PinChangeInterrupt library is reported as working under MicroCore issue #42, it took some time to finigure out why.

I raised the issue with example here:
https://github.com/NicoHood/PinChangeInterrupt/issues/41#

Looking through the MircoCore sources, I found that sei() is only added where interrupts are used, hence my question.

**Comment by MCUdude** [comment]
Thanks for reporting! Interrupts should be enabled by default. I'll fix it right away!
