### ISSUE TITLE
delayMicroseconds() does not support variables

### ISSUE THREAD

**Issue by UnforeseenOcean** [MCUdude/MicroCore#129]
Example code:
```cpp
#define FLICKER_LED_PIN 0
void setup() {
  pinMode(FLICKER_LED_PIN, OUTPUT);
} 
static uint16_t y16 = 1;
uint8_t xor_rand() {
  y16 ^= (y16 << 13);
  y16 ^= (y16 >> 9);
  return (y16 ^= (y16 << 7))&255;
}
void loop() 
{
  static byte dir = 0;
  static byte start  =  0;      
  static byte finish;
  if(!dir)
  {
    finish = 224 + (xor_rand()>>3);
  }
  else
  {
    finish = 160 + (xor_rand()>>2);
  }
  
  for (byte i = start; (!dir)?(i<finish):(i>start); (!dir)?i++:i--) {
    analogWrite(FLICKER_LED_PIN, i);
    delayMicroseconds(873 + (xor_rand()>>1));
  }
  delay(30 + (xor_rand()>>2));
  dir = !dir;
  start = finish;
}
```

Results in this error.
![IMG1627541772](https://user-images.githubusercontent.com/11834016/127446009-1cd833d0-012a-458a-96ea-8a5a72d261a0.png)

**Comment by MCUdude** [comment]
That is to be expected, the delay has to be known at compile time. Is done this way to keep the size of the compiled code small.

If you need to change the delay at runtime, just create a function that takes a parameter, counts down and executes delayMicroseco ds(1) every time it counts down.

**Comment by MCUdude** [comment]
Untested, but should work:

```c
void delay_microseconds(uint16_t us)
{
  while(us--)
    delayMicroseconds(1);
}
```

**Comment by UnforeseenOcean** [comment]
The thing that's bugging me is that Core13 supposedly did support this function like Arduino did, since the code was originally written for it. Why would that be?

**Comment by MCUdude** [comment]
Core13 was very poorly optimized in terms of flash usage. This core is very vaguely based on Core13, but pretty much all "Core13 code" has later been replaced. For accuracy and space saving reasons I've decided to make delayMicroseconds require a parameter known at compile time.

**Comment by nerdralph** [comment]
picoCore's delayMicroseconds() works with variable delays and still has a very small codesize.
https://github.com/nerdralph/picoCore/blob/master/avr/cores/picocore/Arduino.h#L68

**Comment by MCUdude** [comment]
@nerdralph that's very clever! Do you mind if I borrow your code?

**Comment by nerdralph** [comment]
It's open source, so copy away.  Imitation is the sincerest form of flattery.

**Comment by MCUdude** [comment]
Excellent! Quick question. I'm having trouble moving the actual function implementation to the Wiring.c fine while still maintaining static inline.

Any idea how to do it properly?

Arduino.h
``` c
 __attribute__((always_inline)) static inline void delayMicroseconds(uint16_t us);
```

wiring.c
``` c
__attribute__((always_inline)) static inline void delayMicroseconds(uint16_t us)
{
  // If us is a compile-time constant result is accurate to 1 cycle
  if(__builtin_constant_p(us))
  {
    _delay_us(us);
    return;
  }

  // When us is not known at compile time, delay is accurate to +/- 2us
  // plus an overhead of 3 CPU cycles
  const float fMHz = (F_CPU/1000000.0);
  // Subtract two for rounding before dividing by 4
  us -= 2;
  delay4us:
    // Delay 4us per loop, less 4 cycles for overhead
    _delay_us(4.0 - (4.0 / fMHz));
    asm volatile ("sbiw %[us], 4" : [us]"+d"(us));
  asm goto( "brpl %l[delay4us]" :::: delay4us);
}
```

I've tried removing the attribute and inline from the wiring.c file, but I'm still getting errors where avr-gcc complains that it's not able to inline:

```
/Users/hans/Documents/Arduino/hardware/MicroCore/avr/cores/microcore/Arduino.h:102:53: error: inlining failed in call to always_inline 'delayMicroseconds': function body not available
   __attribute__((always_inline)) static inline void delayMicroseconds(uint16_t us);
```

**Comment by nerdralph** [comment]
I don't think you'll be able to do it completely outside the header.  That's why I have it in Arduino.h.
You could move the runtime part to a separate function, say delayVariableMicros(), and in Arduino.h, add an else block to the "if(__builtin_constant_p(us))" to call delayVariableMicros().
Personally,  I prefer keeping the whole function definition in the header so you can see the code all in one place.  Some say it's bad style, but for small code blocks I think it's better my way since it is easier to maintain code in one file rather than two.

With LTO, the compiler may be able to constant parameter checks during link time, but I couldn't get __builtin_constant_p(us) to work outside a header.
