### ISSUE TITLE
No programmer on Arduino 2

### ISSUE THREAD

**Issue by kamilbystryk** [MCUdude/MicroCore#147]
On Arduino 1.x everything it's OK, but on Arduino 2 I don't see "Arduino as ISP (micro code)" programmer. In this case, when I choose "Arduino asISP" i can only write bootloader, but I can't write program. How can I fix it?
![image](https://user-images.githubusercontent.com/36157364/229414308-dd9545e9-2404-491a-8911-9ebe16a110eb.png)

**Comment by MCUdude** [comment]
Have you installed MicroCore using the boards manager install? I have no issues running "Burn Bootloader" from IDE 2.0.4

<img width="637" alt="image" src="https://user-images.githubusercontent.com/3238730/231006244-a5705ca3-0899-4b3d-9f01-c0a766989091.png">

**Comment by mcuee** [comment]
No issues here using Board Manager with latest Arduino IDE 2.1.0 under Windows 11.

**Comment by mcuee** [comment]
I think this issue can be closed.
