### ISSUE TITLE
insomnia - if millis() is used it does not enter sleep mode

### ISSUE THREAD

**Issue by kratochviljan** [MCUdude/MicroCore#149]
If the millis() function is used then it is not possible to enter sleep mode.

Interestingly, even if the sleep is done right at the beginning in the setup() function and the millis() is used later in the function that is called from the main loop(), it still fails to enter the sleep mode.

Just comment out line 19 - the call to killsleep(), which uses the millis() function, and everything works correctly.
The MCU goes into sleep mode immediately after reset, where it stays until the button is pressed.

![image](https://user-images.githubusercontent.com/6692391/230743165-d9dfc5d5-8384-47a9-8d0b-55ca62937136.png)

```
#include <avr/sleep.h>
#include <avr/interrupt.h>

#define ledPin 0
#define buttonPin 1

void setup() {
  
  pinMode(ledPin, OUTPUT);
  digitalWrite(ledPin, LOW);
  pinMode(buttonPin, INPUT_PULLUP);

  mcuSleep();
}

void loop() {

  blink();
  killsleep(); // comment this line  
}


void mcuSleep(){
  sei();
  sleep_enable();
  attachInterrupt(digitalPinToInterrupt(buttonPin), wakeInterrupt, LOW);
  delay(100);
  set_sleep_mode(SLEEP_MODE_PWR_DOWN);
  sleep_mode();
  //sleep here
  sleep_disable();
  delay(100);
  detachInterrupt(digitalPinToInterrupt(buttonPin));
}

void wakeInterrupt(void){
// NOP
}


void blink(void) {

    digitalWrite(ledPin, HIGH);
    delay(1000);
    digitalWrite(ledPin, LOW);
    delay(1000);  

}

void killsleep (void) {

  uint32_t now = millis();
  
}
```

**Comment by MCUdude** [comment]
millis() runs off the internal watchdog timer. Can you try to disable watchdog interrupts before entering sleep mode?

```c
WDTCR &= ~(1 << WDTIE);
```

**Comment by pklosko** [comment]
Hello Jan,  
my sleep funcion work fine @ attint13 :

int sleepIn(void) {
  if (DDRB != 0){
    ddr = DDRB;
  }
  if (DIDR0 != 0x3F){
    dir = DIDR0; 
  }
  DDRB = 0;                            // All lights off
  PORTB = 0x1F;                        // Pullups on
  DIDR0 = 0x3F;                        //Disable digital input buffers on all unused ADC0-ADC5 pins.
  ADCSRA &= ~(1<<ADEN);                //Disable ADC
  ACSR = (1<<ACD);                     //Disable the analog comparator
  cli();                               //Deactivate Interrupts as long as I change Bits      
  GIMSK |= (1<<INT0);                  // Enable Pin Change Interrupts
  set_sleep_mode(SLEEP_MODE_PWR_DOWN); // go to deep sleep
  MCUCR &= ~(1 << ISC00);              //Set low level Interrupt
  MCUCR &= ~(1 << ISC01);              //Set low level Interrupt
  sei();                               //Activate Interrupts
 //go to sleep
  sleep_mode();
  //and wake up
  cli();          //Deactivate Interrupts
  return 1;
}

**Comment by kratochviljan** [comment]
@pklosko - there is no problem with the sleep routine, it works fine if the millis() function is not used

@MCUdude  - thank you, disabling watchdog interrupts solves the problem.
After waking up you have to turn it on again, otherwise millis() doesn't work, but that's obvious...
I'm listing here my sleep() function, which puts the mcu to sleep and then wakes it up by pressing a button, maybe that will help someone. 

![image](https://user-images.githubusercontent.com/6692391/230777570-e77b1454-4eda-409b-b722-6ec376156115.png)

```
void mcuSleep() {

  // because of the implementation of the millis() function it is necessary
  // to disable the watchdog interrupt before entering sleep mode
  WDTCR &= ~(1 << WDTIE);
   
  set_sleep_mode(SLEEP_MODE_PWR_DOWN);
  noInterrupts(); // for the sake of keeping exact timing
  sleep_enable();
  attachInterrupt(digitalPinToInterrupt(buttonPin), wakeInterrupt, LOW);
  interrupts(); // enable interrrupts again
  sleep_cpu(); // here the cpu is put to sleep
  //Chrrrr, chrrrr
  sleep_disable(); // and here he wakes up again
  delay(100);
  detachInterrupt(digitalPinToInterrupt(buttonPin));

  // after waking the cpu from sleep mode it is necessary to enable
  // the watchdog interrupt again, otherwise the millis() function does not work
  WDTCR |= (1 << WDTIE);
}
```

**Comment by MCUdude** [comment]
Great to hear you figured it out!
