### ISSUE TITLE
PlatformIO: `-DCUSTOM_BAUDRATE` wrong documentation

### ISSUE THREAD

**Issue by LoZioo** [MCUdude/MicroCore#157]
While using PlatformIO + MicroCore, I noticed the parameter `-DCUSTOM_BAUDRATE` is misspelt and should be `-DCUSTOM_BAUD_RATE`.

As a result, I couldn't set a custom baud rate using PlatformIO, but only with the Arduino IDE...

**Comment by MCUdude** [comment]
Thanks for reporting! Fixed in 2f6e868
