### ISSUE TITLE
Cannot find plugin liblto_plugin-0.dll

### ISSUE THREAD

**Issue by beicnet** [MCUdude/MicroCore#24]
Using:
 Arduino IDE 1.8.2
MicroCore 1.0.2

Error message:

```
C:\Users\Pc\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.8.1-arduino5/bin/avr-gcc-ar: Cannot find plugin 'liblto_plugin-0.dll'

exit status 1
Error compiling for board ATtiny13.
```

**Comment by MCUdude** [comment]
Have a look at issue #13 and #20. You need avr-gcc 4.9.2 to use MicroCore

**Comment by beicnet** [comment]
Aha, okay, I just zipped and then deleted the "4.8.1-arduino5" folder and has been solved!
Thank you!
