### ISSUE TITLE
Code freezes Attiny

### ISSUE THREAD

**Issue by caiopoit** [MCUdude/MicroCore#25]
Any idea why this code does not work with micro core even though it compiles?
https://forum.arduino.cc/index.php?topic=483961.0

```c++
unsigned long previousMillis = 0;
#define interval 1000
/////////////////////////////////////////////////////////
void Blink();

void setup() {
  OSCCAL += 3;
  pinMode(3, INPUT);
  pinMode(0, OUTPUT);
  pinMode(4, INPUT);
  pinMode(1, OUTPUT);
}
/////////////////////////////////////////////////////////
void loop() {

  if (pulseIn(3, HIGH, 1000000) > 1500) {
    digitalWrite(0, HIGH);
  }
  else {
    digitalWrite(0, LOW);
  }

  if (pulseIn(4, HIGH, 1000000) > 1500) {
    Blink();
  }
  else {
    digitalWrite(1, LOW);
  }
}
//////////////////////////////////////////////////////////
void Blink() {

  if (millis() - previousMillis >= interval) {
    digitalWrite(1, HIGH);
    delay(70);
    digitalWrite(1, LOW);
    delay(200);
    digitalWrite(1, HIGH);
    delay(70);
    digitalWrite(1, LOW);
    previousMillis = millis();
  }
}
```

**Comment by MCUdude** [comment]
You probably need to enable micros in the core settings file. pulseIn depends on it

**Comment by caiopoit** [comment]
It is enabled.

**Comment by MCUdude** [comment]
I'm not able to do any testing in the near future. Try to isolate to issue as much as possible by removing everything unnecessary. Then find out where the code freezes, and which line that causes it.
Good luck 🙂

**Comment by caiopoit** [comment]
The parts of the code work when they are splited, that is why it is strange.

**Comment by caiopoit** [comment]
No one has an idea? It would be really helpful.

**Comment by smeezekitty** [comment]
Is it actually freezing or is it getting stuck in a loop in pulseIn?

**Comment by caiopoit** [comment]
How am I supposed to check those two options? I don't know wich one is actually occurring...

**Comment by MCUdude** [comment]
I'm working on a new implementation of pulseIn which does depend on micros() to work. Does your code run if you replace pulseIn with pulseInNew?

``` c++
uint32_t pulseInNew(uint8_t pin, uint8_t state, uint32_t timeout) 
{  
  uint32_t width = 0; // Keep initialization out of time critical area
  
  // Convert the timeout from microseconds to a number of times through
  // the initial loop; it takes 16 clock cycles per iteration.
  uint32_t numloops = 0;
  uint32_t maxloops = microsecondsToClockCycles(timeout) >> 4; // Divide by 16

  // Wait for any previous pulse to end
  while (!!(PINB & _BV(pin)) == state)
  {
    if(numloops++ == maxloops) {return 0;}
    asm("nop \n");  
    asm("nop \n");
  }
  // Wait for the pulse to start
  while (!!(PINB & _BV(pin)) != state)
  {
    if(numloops++ == maxloops) {return 0;}
    asm("nop \n");  
    asm("nop \n");
    asm("nop \n");
  }
  // Wait for the pulse to stop This loop is 16 instructions long
  while (!!(PINB & _BV(pin)) == state)
  {
    if(numloops++ == maxloops) {return 0;}           
    width++;
    asm("nop \n");  
    asm("nop \n");  
    asm("nop \n"); 
  }

  // Convert the reading to microseconds. 
  return clockCyclesToMicroseconds(width << 4); // Same as multiplying by 16
}
```

~~I'm not finished tuning the timeout~~ timeout is now tuned and the timing is pretty darn accurate! Note that you'll have to enable LTO in order for the function to work.

**Comment by caiopoit** [comment]
I get this error:

> 
Build options changed, rebuilding all
C:\Users\Caio Poit\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.8.1-arduino5/bin/avr-gcc-ar: Cannot find plugin 'liblto_plugin-0.dll'

exit status 1
Error compiling for board ATtiny13.

My ICG is 4.8.1, how do I get the proper one?
And about the code above, I just updated the microcore, does it come with the newer version?

**Comment by mcuee** [comment]
Old issue like this can probably be closed.
