### ISSUE TITLE
avrdude: Can't find programmer id "{upload.protocol}"

### ISSUE THREAD

**Issue by knobik** [MCUdude/MicroCore#32]
Im using exacly this settings

![image](https://user-images.githubusercontent.com/795254/30520446-f8d8f196-9bad-11e7-931b-7ddf6e62e311.png)

on Arduino IDE 1.8.2

and in the end while trying to program the attiny13 im getting this error message.

avrdude: Can't find programmer id "{upload.protocol}"

in commandline i noticed the IDE did not replace the -c{upload.protocol} with a variable.

**Comment by MCUdude** [comment]
Are you using the latest version of MicroCore; v1.0.2 or a fresh manual install?

**Comment by knobik** [comment]
Lastest version 1.0.2 installed from package manager

**Comment by MCUdude** [comment]
It's an issue with the IDE. You can read more about it [here](https://github.com/MCUdude/MicroCore/issues/3). 
What you can do is choose **Arduino as ISP** instead. If you need a slower programmer you can edit the Arduino as ISP sketch directly.

**Comment by MCUdude** [comment]
I'm closing this issue as we allready have issue #22 and issue #3 open
