### ISSUE TITLE
attachInterrupt() example needed

### ISSUE THREAD

**Issue by KochkinBochkin** [MCUdude/MicroCore#35]
Hello! Please add the attachInterrupt(interrupt, function, mode) example. I tried many options, but I did not succeed with external interrupts with Attiny13. Thank you.

**Comment by MCUdude** [comment]
AttachInterrupt works exactly the same as it does on any other Arduino. The code below will toggle an LED connected to pin 2 if the interrupt pin (pin 1) is connected to ground.

``` c
const uint8_t ledPin = 2;
const uint8_t interruptPin = 1;
volatile uint8_t state = LOW;

void setup() {
  pinMode(ledPin, OUTPUT);
  pinMode(interruptPin, INPUT_PULLUP);
  attachInterrupt(digitalPinToInterrupt(interruptPin), blink, CHANGE);
}

void loop() {
  digitalWrite(ledPin, state);
}

void blink() {
  state = !state;
}
```

**Comment by KochkinBochkin** [comment]
Thank you very much!
