### ISSUE TITLE
Support for digitalPinToBitMask

### ISSUE THREAD

**Issue by thomaskilian** [MCUdude/MicroCore#37]
I'm using a lib which utilizes `digitalPinToBitMask`. I once programmed an Attiny13 that used a lib (and it's working still) using this operation. Now I wanted to update it and tried compiling with this MicroCore. But obviously the operation is not implemented here. Is there any way to get this to work? Or am I forced to google/voodoo whatever I did once I got my code working?

**Comment by MCUdude** [comment]
Sorry, I should probably implement it to keep the compability with other Arduino sketches as good as possible. Try adding:

```c
#define digitalPinToBitMask(p)  (((p) >= 0 && (p) <= 5) ? _BV(p) : -1)
```

**Comment by thomaskilian** [comment]
`digitalPinToPort` would be the next one. (I'm out for some hours now...)

**Comment by MCUdude** [comment]
Most of these macros are [All ready implemented](https://github.com/MCUdude/MicroCore/blob/d58d051039a1eb11b1bf6b842f0d2cdb8f0728fa/avr/cores/microcore/pins_arduino.h#L32). You just need to do a manual installation of MicroCore, because I haven't doe a release of it yet.

**Comment by thomaskilian** [comment]
I manually included that header and it throws a couple of `error: redefinition of 'const uint8_t MOSI'
 static const uint8_t MOSI = 0;` errors. Probably I can ignore them?

**Comment by thomaskilian** [comment]
Hmm. Commented the above and now it croaks `'digitalPinToBitMask' was not declared in this scope`

**Comment by thomaskilian** [comment]
Ok. I included the `digitalPinToBitMask` and the `pins_arduino.h` manually, commented the duplicate definitions of `MISO` etc. and now it croaks `undefined reference to `micros'`

**Comment by MCUdude** [comment]
You'll have to enable Micros() if your code depends on it. Read the **core settings** section in the README file for more info

**Comment by thomaskilian** [comment]
That did it. Now I just have to figure out why my code uses up 400% of the available memory although I did not change much :-/

**Comment by MCUdude** [comment]
Make sure LTO is enabled. That helps a lot on the compiled code size. I'll close this issue as soon as I've implemented the digitalPinToBitMask macro

**Comment by thomaskilian** [comment]
Yeah, I'll look into that. But I guess my main issue is that I used a 45 and not a 13 - LOL. Thanks for the support and I'll find another application for the 13 soon :-) 
👍
