### ISSUE TITLE
Output different than 0 does not work and voltage leak?

### ISSUE THREAD

**Issue by piotrkochan** [MCUdude/MicroCore#38]
Hi, using basic blink program I can use only pin 0 (PB0). Others pins does not work.
Also, when I try to use different pin, pin 0 still BLINKS but with lover voltage on the output. This issue makes MicroCore totally useless to me.

**Comment by MCUdude** [comment]
That seems very strange. Please post the code you are using and a picture of your hardware setup. Makes it much easier for me to help you track down the issue 👍

**Comment by piotrkochan** [comment]
It was code issue :) Everything is ok

**Comment by MCUdude** [comment]
Good!
