### ISSUE TITLE
SoftwareSerial.h No such file or directory

### ISSUE THREAD

**Issue by ljcucc** [MCUdude/MicroCore#51]
I would like to try the UART on ATtiny13, then I got this error. What is going on ?

Thanks!

**Comment by beicnet** [comment]
@ljcucc It's because you need to download the SoftwareSerial library separately and the second thing is that you will get out of space right away!

**Comment by MCUdude** [comment]
The ATtiny13 don't support the regular software serial library because of its limited resources (64B RAM, 1024B flash). If you want to implement serial you may use this [method](http://nerdralph.blogspot.no/2014/01/avr-half-duplex-software-uart.html).
