### ISSUE TITLE
PlatformIO support

### ISSUE THREAD

**Issue by latonita** [MCUdude/MicroCore#52]
It would be fantastic to organize this lib as downloadable platform for PlatformIO

**Comment by MCUdude** [comment]
Now that MightyCore, MegaCore, MiniCore, and MajorCore are available through PlatformIO, I think it's about time that we get MicroCore support as well.

I can't give you an exact date, but I will work together with the PlatformIO developers to make sure it is highly configurable through platformio.ini, and that you can set fuses directly in PlatformIO.

**Comment by MCUdude** [comment]
PlatformIO support is now ready!
