### ISSUE TITLE
my atmega328 (uno) .2 PWM 180 degree phase .code dont work with tiny

### ISSUE THREAD

**Issue by majidmp97** [MCUdude/MicroCore#69]
hello
my cod work in atmega328 uno but i try to work with your micro core for tiny 13 but i have error register and don't work
2 PWM 180 degree phase

`#include "TimerOne.h"               // include TimerOne.h

**Comment by beicnet** [comment]
Your code will never fit in ATtiny13 anyway, also it's not gonna work because of your Pin numbering.

**Comment by MCUdude** [comment]
* ATtiny13 doesn't have a hardware serial port. Serial.print will never work.
* ATtiny13 only has one timer; timer0. Timer1 will never work
* ATtiny13 only has 5 IO pins you can use.

You can't just expect any program to run on the ATtiny13. In most cases it needs to be written spesifically for the hardware. Remember it only has 1k of flash and 64B of RAM. If you need help porting your code please use the Arduino forum instead.
