### ISSUE TITLE
Getting to work with Standalone AVR programmer

### ISSUE THREAD

**Issue by witnessmenow** [MCUdude/MicroCore#72]
Hey,

First thanks for the core, really useful!

I'm trying to use the [Standalone Arduino AVR ISP programmer](https://github.com/adafruit/Standalone-Arduino-AVR-ISP-programmer) so I have a dedicated device for burning an image onto my Attiny13 but it isn't working for me and I was wondering if you might be able to offer any suggestions

I have the MicroCore set up and its working fine with Arduino as ISP if I burn the bootloader and then upload sketch.

When using the standalone programmer, it fails to upload the sketch. It attempts to write the hex of the sketch, but fails verification and the sketch does not function either (doesn't blink the Led). It does delete the existing sketch so its doing something at least!

I tried to figure out what fuses to use in the configuration of the standalone programmer by seeing what was in the verbose output when burning the bootloader and when uploading the sketch. (To be honest this stuff is brand new to me)

Could someone please take a look to see if there is anything you could suggest I try differently?

```const image_t PROGMEM image_328 = {
    // Sketch name, only used for serial printing
    {"PCB3.hex"},
    // Chip name, only used for serial printing
    {"ATtiny13"},
    // Signature bytes for 328P
    0x1e9007,
    // Programming fuses, written before writing to flash. Fuses set to
    // zero are untouched.
    {0x3F, 0x3A, 0xFF, 0xFF}, // {lock, low, high, extended}
    // Normal fuses, written after writing to flash (but before
    // verifying). Fuses set to zero are untouched.
    {0x0, 0x0, 0x0, 0x0}, // {lock, low, high, extended}
    // Fuse verify mask. Any bits set to zero in these values are
    // ignored while verifying the fuses after writing them. All (and
    // only) bits that are unused for this atmega chip should be zero
    // here.
    {0x3F, 0x3A, 0xFF, 0xFF}, // {lock, low, high, extended}
    // size of chip flash in bytes
    1024,
    // size in bytes of flash page
    32,
    // The actual image to flash. This can be copy-pasted as-is from a
    // .hex file. If you do, replace all lines below starting with a
    // colon, but make sure to keep the start and end markers {R"( and
    // )"} in place.
    {R"(
:mySketchInHex
    )"}
};
```

**Comment by MCUdude** [comment]
Sorry for the incredibly late reply. I have no experience with the Standalone AVR loader, but it clearly seems like an issue with the loader and not MicroCore. I suggest you open an issue over at their repo instead. I'm sure they can help you figure this out.
