### ISSUE TITLE
Unclear usage of ADC

### ISSUE THREAD

**Issue by harrylisby** [MCUdude/MicroCore#73]
I've been looking for the adc macros, and there isn't. Am I missing them somewhere or they are not implemented yet?

Looking for something like in other arduinos "A0, A1 ... "

**Comment by MCUdude** [comment]
Definitions of A0-A3 can be found in the [pins_arduino.h](https://github.com/MCUdude/MicroCore/blob/95243232f489dfbe9e982aa751cc368ba6ce53e4/avr/variants/attiny13/pins_arduino.h#L71-L75) file.

The AnalogRead function can be found in the [wiring_analog.c](https://github.com/MCUdude/MicroCore/blob/1a7a5367ddbff47827f1813578f3ca2106dd80af/avr/cores/microcore/wiring_analog.c#L28-L64) file
