### ISSUE TITLE
[Feature Request - Easy] Include arduino core "binary.h" in your core

### ISSUE THREAD

**Issue by Sorontik** [MCUdude/MicroCore#74]
Hello,

i was just mocking about with different settings on my ATTiny13A and stumbled over the fact that i wasn't able to use the 'B' prefix to define values in binary form.

Now i found that arduino solved this in their binary.h by just adding an #define for each possible (up to eight bit) binary expression.

I suggest to copy this header to your core, because it would be very convenient, but as the definitions are processed and replaced at compile time it would not affect any performance/size issues.
(Besides adding approx. 11kB to the package) ;)

I don't think such a minor change is worth the effort/overhead of a pull request, so i just write the issue ;)

best regards
Soro

PS: your library are really nice, thank you :D

**Comment by MCUdude** [comment]
Sure, I've totally forgot to add binary.h.
Personally I prefer to use the ANSI C `0b` prefix instead, but this core is supposed to be arduino compatible!
