### ISSUE TITLE
idea: include PCINT0 interrupt in Winterrupts.c

### ISSUE THREAD

**Issue by jmerc77** [MCUdude/MicroCore#81]
including PCINT0 interrupt in Winterrupts.c for more options would be cool.
so far only the global interrupt is used for pins.
my compiled example attached.
[WInterrupts.zip](https://github.com/MCUdude/MicroCore/files/3287794/WInterrupts.zip)

note: EXTERNAL_NUM_INTERRUPTS and digitalPinToInterrupt in pins_arduino.h will need updating too.

PS: tried to pull but was unable to oddly.

**Comment by MCUdude** [comment]
It's a good idea, but it comes with some issues as well.
First, it's not supported bu the official Arduino API. This means this core has some funtionality that other cores don't.  
Second, the PCINT ISR will trigger on a pin state change, while users of the attachInterrupt function wil most likely expect support for falling and rising as well. This can be acheived with some boolean magic though.  
Third; what if I want to use two PCINT pins and let them trigger two separate functions? Then we would have to increase the intFunc to match this.  
Finally, doing all this causes alot of overhead. The Tiny13 is very short on flash, and the Winterrupts.c file adds 78 bytes extra for this example sketch.

```c
const byte ledPin = 0;
const byte interruptPin = 1;
volatile byte state = LOW;

void setup() {
  pinMode(ledPin, OUTPUT);
  pinMode(interruptPin, INPUT_PULLUP);
  attachInterrupt(digitalPinToInterrupt(interruptPin), blink, CHANGE);
}

void loop() {
  digitalWrite(ledPin, state);
}

void blink() {
  state = !state;
}
```

Again, I really appreciate your contribution, but it's very difficult to add more functionality to this core without also adding overhead.
