### ISSUE TITLE
make millis() interrupt safe

### ISSUE THREAD

**Issue by nerdralph** [MCUdude/MicroCore#82]
I just realized millis() can seem to count backwards if the millis ISR runs while the function is called.  It's extremely unlikely to happen, but it is technically possible.  Adding cli/sei is all it needs:
```c
  uint32_t m;
  cli();
  m = wdt_interrupt_counter;
  sei();

  return m;
```

**Comment by MCUdude** [comment]
Sorry for the late response! It totally slipped through. It's fixed now, thanks!
