### ISSUE TITLE
add better option to disable millis()

### ISSUE THREAD

**Issue by Ma5t3rful** [MCUdude/MicroCore#83]
first sorry for my poor English.
hello can you add another option to disable/enable millis() ?
changing the  core_settings.h every time is so boring you can do something like this ability in the FastLED library:
`#define FASTLED_ALLOW_INTERRUPTS 0 //disables interrupt i love it` 
or you can add an option to disable or enabling millis() like this one:
![](http://uupload.ir/files/cim4_contex.png)
thank you.

**Comment by MCUdude** [comment]
Thanks for the input! I totally agree with you. In many cases you don't need millis/micros, and they also do occupy alot of flash memory. I'll see what I can do. Stay tuned!
