### ISSUE TITLE
always use LTO, remove option

### ISSUE THREAD

**Issue by nerdralph** [MCUdude/MicroCore#90]
The standard Arduino core has been using LTO by default for the last several releases.  I think it's safe to say that Arduino libs and sketches are expected to compile and run with LTO.  Therefore I suggest removing the option and making it the default.
It would simplify the menus, and simplify using the core as users would not think they have to test their code with and without LTO.

**Comment by MCUdude** [comment]
I agree. There's really no reason not to enable LTO when compiling for a target so limited as the ATtiny13. I'll fix it soon!
