### ISSUE TITLE
improvement: only enable PWM in analogWrite()

### ISSUE THREAD

**Issue by nerdralph** [MCUdude/MicroCore#91]
When testing the OSCCAL routine, I noticed timer/counter0 is setup for PWM in init(), even when analogWrite is never used.  Moving the PWM setup to analogWrite would save a bit of flash (8 bytes) when not using analogWrite.  It would also mean that code that is using the timer/counter for other purposes won't have to reset the registers before using them.

**Comment by MCUdude** [comment]
Thanks! Will look into this!
