### ISSUE TITLE
Transparent millis support?

### ISSUE THREAD

**Issue by MCUdude** [MCUdude/MicroCore#94]
To quote @nerdralph from #89:

> ..... Just before you added the issue for HalfDuplexSerial, I had almost finished transparent millis() support. When you call millis() in your sketch, millis.S get linked in, and when you don't call it, it gets left out. I also optimized the millis() function using inline asm. The last thing I need to do is move the millis init code (WDTCR & sei) out of wiring.c into millis.S.

Transparent millis (and maybe micros in the future?) support would be awesome. This means that there wouldn't any need for a dedicated menu option to enable/disable millis, it happens automatically if either is called in the user program. Fewer options for users to deal with equals more user-friendliness IMO.

**Comment by nerdralph** [comment]
It works, but I've run into some merge conflicts with your latest push.  I should have it sorted out by tomorrow, so I can send you a pull request as an early Xmas present. :-)

**Comment by nerdralph** [comment]
As promised.
https://github.com/MCUdude/MicroCore/pull/95

**Comment by MCUdude** [comment]
Thanks! I'll look into it soon. For obvious reasons, I have limited time for this stuff today 😉

**Comment by nerdralph** [comment]
BTW, here's the blink-millis sketch I used for testing the millis changes.
https://gist.github.com/nerdralph/8af5ade84839f4cc3256faa470434db8
