### ISSUE TITLE
identify MicroCore version

### ISSUE THREAD

**Issue by nerdralph** [MCUdude/MicroCore#98]
I was looking into this recent issue:
https://github.com/MCUdude/MicroCore/issues/97
With a few recent MicroCore versions having been pushed to git, I was trying to figure out how to tell which version a user has.  The Arduino IDE adds -DARDUINO=10810 to the build, so I was thinking of something similar like -DMICROCORE=10004.
I'd also suggest incrementing the minor subversion (currently 4) on every push to master, and the major subversion (currently 0) on every release.
Perhaps consider following a versioning standard such as https://semver.org/

**Comment by MCUdude** [comment]
The standard for Arduino core packages is to increment the number on every release. TBH it's to much hassle changing the version number every time I do a commit. However, I could be better at doing releases more often.
